version: '3.8'

services:
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - mongo
    env_file:
      - .env

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: docker/prod/Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_APP_API_URL: ${API_URL}
      # PORT: ${FRONTEND_PORT}

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
